FROM scratch AS ctx
COPY / /

FROM quay.io/fedora/fedora-toolbox:41 

ARG BITWIG_VERSION=5.3.8
ARG YABRIDGE_VERSION=5.1.1
ARG WINE_VERSION=9.21

RUN --mount=type=bind,from=ctx,src=/,dst=/ctx \
    cd /ctx/rpm_builder && \
    dnf5 install -y make && \
    make install-development-dependecies-fedora && \
    make build && \
    dnf5 install -y /tmp/bitbox-convertion/bitwig-studio-*.x86_64.rpm